#pragma once
#include <string>
#include <windows.h>
#define MAX_MSG_LENGTH 256
void Main();
extern "C" __declspec(dllexport) void DllExport();
void isMapName();
void SendTeleport();
namespace hook
{
    void camera_limit();
    void cmd();
    void Coutdown();
    void custom_game();
    void gui();
    void item_icon();
    void name_color();
    void packet();
    void quick_slot();
    void RaidClassCounter();
    void title();
    void vehicle();
    void is150RaidSlot();
    void Buttons();
    void EnableRessOptions();
    void EventModeMain();
    void SendObjects(); 
    void sentCommandCountryMain();
    void Shiftx10();
    void AntiCheat();
    void SahProtect();
    void GraphicOptions();
    void FpsBoost();
    void isSmallIcon();
    void DebuffSeparate();
    void mainRes();
    void ShiftTagRaidMenssage();
    void SeeOrangeStatus();
    void AllocEffects();
    void TeleportButton();
    void CostumeEffect();
    void viewID();
    void viewMonsterDrops();
    void FeedHook();
    void RessLocalTimerMain();
    void HoldShiftEnableKeyBar();
}
void hpmode();
extern DWORD sendPosText;
extern DWORD loadText;
extern std::string pos_x_stack[128];
extern std::string buff_stack[128];
extern std::string isPos[128];
extern std::string stack[128];
extern int raid_pointer;
extern std::string pvp_list[255];
extern std::string check_btn[255];
extern char pointer_true_false[255];
extern char esp_20[255];
extern char get_pos_y_2[255];
extern char get_pos_x_2[255];
extern char register_pos[255];
extern std::string savePosY2[48];
extern std::string savePosX2[48];
extern DWORD isRenderMouseClick;
extern DWORD isRenderObjectSingle;
extern DWORD isPosX;
extern DWORD isPosY;
extern DWORD isSavePosX;
extern DWORD isSavePosY;
extern DWORD isMousePosX;
extern DWORD isMousePosY;
extern char save_pos_y_2[48];
extern char save_pos_x_2[48];
extern DWORD isPosX_2;
extern DWORD isPosY_2;
extern BYTE auraEffect;
extern std::string paginationCount;
extern DWORD isPressed;
extern DWORD pointer_close;
extern DWORD pointer_open_close;
extern DWORD largura;
extern DWORD altura;
extern DWORD isPointerPagination;
extern std::string warMove[255];
extern std::string teleportButton[255];
extern std::string closeButton[255];
extern LPCSTR isMap1;
extern LPCSTR isMap2;
extern LPCSTR isMap3;
extern LPCSTR isMap4;
extern LPCSTR isMap5;
extern LPCSTR isMap6;
extern LPCSTR isMap7;
extern LPCSTR isMap8;
extern LPCSTR isMap9;
extern LPCSTR isMap10;
extern LPCSTR isMap11;
extern LPCSTR isMap12;
extern LPCSTR isMap13;
extern LPCSTR isMap14;
extern LPCSTR isMap15;
extern LPCSTR isMap16;
extern std::string battleground[255];
extern std::string debuff[255];
extern std::string isPagination[255];
extern std::string isPagination2[255];
extern std::string isClassIconDPSLoad[255];
extern std::string isClassIconRangeLoad[255];
extern std::string isClassIconMagicLoad[255];
extern std::string isClassIconCureLoad[255];
extern std::string isClassIconBloodLoad[255];
extern std::string isClassIconTankLoad[255];
extern std::string raidFighter[16];
extern std::string flagAllianceLight[16];
extern std::string flagAllianceFury[16];
extern std::string raidDefender[16];
extern std::string raidRanger[16];
extern std::string raidArcher[16];
extern std::string raidMage[16];
extern std::string raidHealer[16];
extern DWORD fadeWindow;
extern DWORD ownSavePosX;
extern DWORD ownSavePosY;
extern BYTE cBoostPointer;
extern BYTE Effects;
extern BYTE Titulo;
extern BYTE cSmall;
extern BYTE small_icon_cmd;
extern BYTE AsaAtivada;
extern DWORD isRenderObject;
extern BYTE PetAtivado;
extern int raid_pointer;
inline int g_showCostumes = false;
inline int g_showFeed = true;
inline int g_showPets = false;
inline int g_showWings = false;
inline int g_showEffects = false;
inline int g_showMobEffects = false;
inline float g_cameraLimit = 65.0f;
extern char KillMsg1[MAX_MSG_LENGTH];
extern char KillMsg2[MAX_MSG_LENGTH];
extern char KillMsg3[MAX_MSG_LENGTH];
extern char KillMsg4[MAX_MSG_LENGTH];
extern char KillMsg5[MAX_MSG_LENGTH];
extern char KillMsg6[MAX_MSG_LENGTH];
extern char KillMsg7[MAX_MSG_LENGTH];
extern char KillMsg8[MAX_MSG_LENGTH];
extern char KillMsg9[MAX_MSG_LENGTH];
extern char KillMsg10[MAX_MSG_LENGTH];
BOOL Write(LPVOID lpAddress, LPVOID lpfn, INT nSize);
BOOL Jump(LPVOID lpAddress, INT lpfn, INT nSize);
void Nop(LPVOID lpAddress, INT nSize);