#ifndef PCH_H
#define PCH_H
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include "sysinfoapi.h"
#include <iostream>
#include <string>
#include <chrono>
#include <thread>
#include <fstream>
#include <exception>
#include <bitset>
#include <hidusage.h>
#include <vector>
#include <typeinfo>
#include <sstream>

#pragma warning(disable: 28159)
#pragma warning(disable: 4996)

#define _CRT_SECURE_NO_DEPRECATE

extern char registerPosChat_y[255];
extern char registerPosChat_x[255];
extern char pointer_true_false_chat[35];
extern char register_pos_chat[35];
extern std::string isCheckChat[255];
extern char packetItem[65];
void ExpandPlayerMemory();
int mainLatency();
void isLatencyHook();
void EleIcon();
void AllocNewEffectFiles();
void AdjustWingInspect();
void Coutdown();
void _3rdSkillBar();
void RightClickNPC();
void ItemInfo();
void BackGround();
void TimeOutSkill();
void DisableCostume();
void AntiCheat();
void ZoomLimit();
void NewMounts();
void GraphicOptions();
void HPBarTitles();
void AllocNewTgaFiles();
extern BYTE Traje_Effect;
void AllocNewEffectFiles();
void AuraEffect();
void NewSlots();
void GetData();
void CharacterScreenSize();
void Thread_Packet();
void RessLeaderandLocal();
extern char pointerOptionTrueFalse[35];
void fpsboost_save();
int saveShiftBar();
void Effects_Save();
void Titulos_Save();
void Small_Icon_Save();
void Traje_Save();
void Alas_Save();
void Pet_Save();
void HP_Dark_Save();
void Traje_Effect_Save();
void HP_Light_Save();
void Fastransit();
void ShowOrangeStatusRecreation();
void HelmetColor();
void AutoRaidMsg();
void NotVanishBuffs();
void SendDelayWingPetCostume();
void Interface_EP5();
void FeedHook();
void HoldShiftEnableKeyBar();
void GetPointerFontSize();
void Packet0501Time();
void SkillDelayFix();
void isFastMain();
void EnemyHP();
void isMainEp6Fix();
void Ep8CharacterScreenBtn();
// void titleText();
void raidSlot();
void SendObjects();
void MainRes();
void FeedGlobal();
extern std::string pos_x_stack[128];
extern std::string buff_stack[128];
extern std::string isPos[128];
extern std::string stack[128];
extern bool isOffline;
extern std::string isOwnKillIcon[255];
extern std::string isOwnKillClose[255];
void isAFKMain();
extern std::string isFace[16];
extern std::string isFace2[16];
extern std::string isFace3[16];
extern std::string isFace4[16];
extern std::string isFace5[16];
extern std::string isFace6[16];
extern std::string isFace7[16];
extern std::string isFace8[16];
extern std::string isRewardBar[16];
extern std::string isRewardCheck[16];
extern std::string isRewardArrow[16];
extern std::string isRewardComplete[16];
extern std::string isRewardBarTime[16];
extern BYTE isFeedEnable;
extern BYTE isShiftEnable;
extern bool globalFeed;
int saveFeed();
void FixNpc();
void FixLagCostume();
void AdjustTrade();
extern char KillMsg1[256];
extern char KillMsg2[256];
extern char KillMsg3[256];
extern char KillMsg4[256];
extern char KillMsg5[256];
extern char KillMsg6[256];
extern char KillMsg7[256];
extern char KillMsg8[256];
extern char KillMsg9[256];
extern char KillMsg10[256];
extern char OwnKillName[70];
void OwnKillTable();
extern char OwnKillName2[70];
extern char OwnKillName3[70];
extern char OwnKillName4[70];
extern char OwnKillName5[70];
extern int raid_pointer;
extern std::string pvp_list[255];

extern char pointer_true_false[255];
extern char esp_20[255];
extern char get_pos_y_2[255];
extern char get_pos_x_2[255];
extern char register_pos[255];
extern std::string savePosY2[48];
extern std::string savePosX2[48];
extern bool globalLight;
extern bool globalDark;
extern bool globalTitle;
extern bool globalBoost;
extern bool globalSmall;
extern bool globalAura;
extern bool globalEffects;
extern bool globalPet;
extern bool globalWing;
extern bool globalCostume;
extern bool global3rdSkillBar;
int is2ndQuickSlotPosSave();
extern DWORD isPosXSkillBar;
extern DWORD isPosXQuickSlot;
extern DWORD isPosYQuickSlot;
extern std::string optionSystemCloseButton[255];
extern std::string isEleWindLoad[255];
extern char rewardGetItemInfo[255];
void WriteIp();
extern BYTE rewardGetCount;
extern std::string isEleFireLoad[255];
extern std::string isEleGroundLoad[255];
extern std::string isEleWaterLoad[255];
extern std::string optionOkButton[255];
extern std::string optionCancelButton[255];
extern char pointerSystemEnabled[35];
extern int ownPointerClose;
extern char isKillFeedMenssage[50];
extern DWORD isPosYSkillBar;
extern bool globalyingDown;
extern bool globalyingDownSkill;
void LSTextSystem();
extern int is3rdSkillBarPosSave();
DWORD WINAPI ThreadMonitoramento(LPVOID lpParam);
extern BYTE Auto_Raid_Command_Pointer;
int main();
extern DWORD mainPosY;
extern DWORD mainPosX;
extern DWORD sendPosText;
extern DWORD fadeWindow;
extern DWORD loadText;
extern DWORD isColor;
extern DWORD ownSavePosY;
extern DWORD ownSavePosX;
void bossWarning();
extern int savePet();
extern int saveWing();
extern int saveCostume();
void DebuffSeparate();
void SahEncryptMain();
void UpdateRangeMain();
void RewarBarMain();
void OptionSystemMain();
void isEnchantFix();
extern BYTE isBuffHolding;
extern std::string optionWindow[16];
extern std::string optionWindowDrop[16];
extern DWORD isRenderObject;
extern DWORD isRenderMouseClick;
void BarIconClass();
void titleText();
extern DWORD isRenderObjectSingle;
extern std::string isSkillBar[16];
extern std::string isSkillBarBG[16];
BOOL Hook(void* pAddr, void* pNAddr, int len = 5);
extern char power[128];
extern DWORD isPosX;
extern DWORD isPosY;
extern DWORD isSavePosX;
extern DWORD isSavePosY;
extern DWORD isMousePosX;
extern DWORD isMousePosY;
extern char save_pos_y_2[48];
extern char save_pos_x_2[48];
extern DWORD isPosX_2;
extern DWORD isPosY_2;
extern std::string warMode15[255];
extern std::string warMode30[255];
extern std::string warMode70[255];
extern std::string paginationCount;
extern DWORD isPressed;
extern std::string optionSystem[255];
extern std::string optionSystemDrop[255];
extern DWORD pointer_close;
extern DWORD pointer_open_close;
extern DWORD largura;
extern DWORD altura;
extern DWORD isPointerPagination;
extern std::string warMove[255];
extern std::string teleportButton[255];
extern std::string closeButton[255];
extern LPCSTR isMap1;
extern LPCSTR isMap2;
extern LPCSTR isMap3;
extern LPCSTR isMap4;
extern LPCSTR isMap5;
extern LPCSTR isMap6;
extern LPCSTR isMap7;
extern LPCSTR isMap8;
extern LPCSTR isMap9;
extern LPCSTR isMap10;
extern LPCSTR isMap11;
extern LPCSTR isMap12;
extern LPCSTR isMap13;
extern LPCSTR isMap14;
extern LPCSTR isMap15;
extern LPCSTR isMap16;
extern char rewarBarSlotGetInfo[30];
extern int duracaoSegundos;
extern float larguraInicial;
extern float larguraFinal;
void WarModes();
extern std::string ownKillTable[32];
void sentCommandCountryMain();
int saveDark();
int saveLight();
int saveAura();
int saveTitle();
int saveEffects();
int saveSmall();
int saveBoost();
void ignoreinfo();
void getAppaerancePacketMain();
void Comandos();
void SendTeleport();
void QuickSlot();
void isMapName();
void checkBoxMain();
void TeleportButton();
void Buttons();
void CheckBoxs();
void HPBar();
void Inventory();
void status_on_off();
void Time();
void Main_Bottom_Bar();
void link_extract_recreation_npc_adjust();
extern DWORD retorno;
extern BYTE Adjust;
extern int isBuffPosSave();
void MonsterPercent();
void EventModeMain();
extern BYTE Adjust_1;
extern DWORD Pos1;
extern DWORD Pos2;
extern DWORD petret1;
extern DWORD petret2;
extern DWORD petre1;
extern DWORD petre2;
extern DWORD returnpet4;
extern DWORD returnpet3;
extern std::string isLoadHPBar[255];
extern std::string itemMallBtn[255];
extern std::string isLoadBG[255];
extern std::string mainBg[16];
extern std::string mouse_hover[16];
extern std::string dex_lapis[16];
extern std::string earth_lapis[16];
extern std::string fire_lapis[16];
extern std::string wind_lapis[16];
extern std::string water_lapis[16];
extern std::string wis_lapis[16];
extern std::string int_lapis[16];
extern std::string rec_lapis[16];
extern std::string sp_lapis[16];
extern std::string hp_lapis[16];
extern std::string luc_lapis[16];

extern bool globalShift;
extern DWORD getPos;
extern int mensagem;
extern int wingoff;
extern int Comand_imput;
extern int  Cmd_retorno;
extern DWORD ocultoasa1;
extern DWORD Asa3return;
extern DWORD returnasa4;
extern DWORD returnpet5;
extern int cmd_jump;
extern DWORD removerasa;
extern DWORD desativar;
extern DWORD saida7;
extern DWORD saida6;
extern DWORD nameReturn;
extern DWORD original;
extern DWORD nameReturn2;
extern DWORD return2;
extern DWORD saida8;
extern DWORD saida9;
extern DWORD saida1;
extern DWORD rev;
extern DWORD rev2;
extern DWORD rev3;
extern DWORD saidaaa;
extern DWORD saida35;
extern DWORD remover;
extern DWORD retornooo;
extern DWORD pet50;
extern DWORD pet51;
extern DWORD oculto;
extern DWORD Remove_Effect;//00416970
/*
*
extern DWORD retorno = 0x41627D;
extern DWORD petret1 = 0x04112AB;
extern DWORD petret2 = 0x004112AB;
extern DWORD petre1 = 0x04112C0;
extern DWORD petre2 = 0x00418310;
extern DWORD returnpet4 = 0x00411228;
extern DWORD returnpet3 = 0x0041814E;
extern int mensagem = 0x0422D40;
extern int wingoff = 0x087D263;
extern int Comand_imput = 0x632BD7;
extern int  Cmd_retorno = 0x4864C6;
extern DWORD ocultoasa1 = 0x0041F505;
extern DWORD Asa3return = 0x0041F4DA;
extern DWORD returnasa4 = 0x0041F5A5;
extern DWORD returnpet5 = 0x00439F26;
extern int cmd_jump = 0x04871D2;
extern DWORD removerasa = 0x0041F76D;
extern DWORD desativar = 0x59FBC5;
extern DWORD saida7 = 0x0043B1DB;
extern DWORD saida6 = 0x43AB66;
extern DWORD nameReturn = 0x59FBB4;
extern DWORD original = 0x914490;
extern DWORD nameReturn2 = 0x478592;
extern DWORD return2 = 0x59F965;
extern DWORD saida8 = 0x439F26;
extern DWORD saida9 = 0x004394AC;
extern DWORD saida1 = 0x439F26;
extern DWORD rev = 0x439F26;
extern DWORD rev2 = 0x43B676;
extern DWORD rev3 = 0x43AC7A7;
extern DWORD saidaaa = 0x43A0CA;
extern DWORD saida35 = 0x0439F33;
extern DWORD remover = 0x004394AE;
extern DWORD retornooo = 0x439F39;
extern DWORD pet50 = 0x00439F26;
extern DWORD pet51 = 0x004394BB;
extern DWORD oculto = 0x0043A0CA;
extern DWORD Remove_Effect = 0x00416830;//00416970

*/


extern BYTE Dark_Pointer;
extern BYTE Light_Pointer;
void ExploitFixs();
void SkillReset();
void RankStat();
void DropList();
void ShiftX10();
extern BYTE Titulo;
extern BYTE cHide;
extern BYTE cBoostPointer;
extern BYTE PetAtivado;
extern BYTE AsaAtivada;
extern BYTE Effect;
extern BYTE cOpen;
extern DWORD Traje_Pointer;
extern std::string battleground[255];
void Cast();
extern std::string debuff[255];
extern std::string isPagination[255];
extern std::string isPagination2[255];
extern std::string isClassIconDPSLoad[255];
extern std::string isClassIconRangeLoad[255];
extern std::string isClassIconMagicLoad[255];
extern std::string isClassIconCureLoad[255];
extern std::string isClassIconBloodLoad[255];
extern std::string isClassIconTankLoad[255];
extern BYTE cSmall;

extern LPCSTR Efeito1;
extern LPCSTR Efeito2;
extern LPCSTR Efeito3;
extern LPCSTR Efeito4;
extern LPCSTR Efeito5;
extern LPCSTR Efeito6;
extern LPCSTR Efeito7;
extern LPCSTR Efeito8;
extern LPCSTR Efeito9;
extern LPCSTR Efeito10;
extern LPCSTR Efeito11;
extern char pet[128];
extern char asaini[128];



#endif